name: Testing, Linting, Vulnerability Checking

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env
          poetry config virtualenvs.create true

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest --cov=random_quiz tests/ --cov-fail-under=60

      - name: Run flake8
        run: poetry run flake8 random_quiz tests --count --show-source --statistics

      - name: Run bandit
        run: poetry run bandit -r random_quiz

