"""empty message

Revision ID: 2e88b04c7a80
Revises: d35512dcf37c
Create Date: 2024-04-30 09:00:15.689044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e88b04c7a80'
down_revision = 'd35512dcf37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('num_questions', sa.Integer(), nullable=False),
                    sa.Column('num_correct', sa.Integer(), nullable=True),
                    sa.Column('id', sa.UUID(),
                              server_default=sa.text('gen_random_uuid()'),
                              nullable=False),
                    sa.Column('dt_created',
                              postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('dt_updated',
                              postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'],
                        name=op.f('fk__quiz__user_id__user'),
                        onupdate='SET NULL',
                        ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__quiz')),
                    sa.UniqueConstraint('id', name=op.f('uq__quiz__id'))
                    )
    op.create_table('question',
                    sa.Column('quiz_id', sa.UUID(), nullable=True),
                    sa.Column('text', sa.TEXT(), nullable=False),
                    sa.Column('correct_answer',
                              sa.Boolean(), nullable=False),
                    sa.Column('question_index',
                              sa.Integer(), nullable=False),
                    sa.Column('id', sa.UUID(),
                              server_default=sa.text('gen_random_uuid()'),
                              nullable=False),
                    sa.Column('dt_created',
                              postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('dt_updated',
                              postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.ForeignKeyConstraint(
                        ['quiz_id'],
                        ['quiz.id'],
                        name=op.f('fk__question__quiz_id__quiz'),
                        onupdate='SET NULL',
                        ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__question')),
                    sa.UniqueConstraint('id', name=op.f('uq__question__id'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('quiz')
    # ### end Alembic commands ###
